name: main

on:
  push:
    branches: [main, test-me-*]
    tags:
  pull_request:

jobs:
  main:
    uses: ./.github/workflows/tox.yml
    with:
      env: '["py39", "py310", "py311", "py312", "py313"]'
